[option]
exclude_paths = []
textwidth = 100
copyright_linenum = 1
copyright_year = "2024"
copyright_holder = "HOLDER"
indent = 2
prefix_inout = "b_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u_"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "ifc_"
re_required_assert = "^[a-z]+[a-z0-9_]*$"
re_required_assert_property = "^[a-z]+[a-z0-9_]*$"
re_required_checker = "^[a-z]+[a-z0-9_]*$"
re_required_class = "^[a-z]+[a-z0-9_]*$"
re_required_function = "^[a-z]+[a-z0-9_]*$"
re_required_generateblock = "^[a-z]+[a-z0-9_]*$"
re_required_genvar = "^[a-z]+[a-z0-9_]*$"
re_required_instance = "^[a-z]+[a-z0-9_]*$"
re_required_interface = "^[a-z]+[a-z0-9_]*$"
re_required_localparam = "^[A-Z]+[A-Z0-9_]*$"
re_required_modport = "^[a-z]+[a-z0-9_]*$"
re_required_module_ansi = "^[a-z]+[a-zA-Z0-9_]*$"
re_required_module_nonansi = "^[A-Z]+[A-Z0-9_]*$"
re_required_package = "^[a-z]+[a-z0-9_]*$"
re_required_parameter = "^[A-Z]+[A-Z0-9_]*$"
re_required_port_inout = "^[a-z]+[a-z0-9_]*$"
re_required_port_input = "^[a-z]+[a-z0-9_]*$"
re_required_port_output = "^[a-z]+[a-z0-9_]*$"
re_required_port_ref = "^[a-z]+[a-z0-9_]*$"
re_required_port_interface = "^[a-z]+[a-z0-9_]*$"
re_required_program = "^[a-z]+[a-z0-9_]*$"
re_required_property = "^[a-z]+[a-z0-9_]*$"
re_required_sequence = "^[a-z]+[a-z0-9_]*$"
re_required_task = "^[a-z]+[a-z0-9_]*$"
re_required_var_class = "^[a-z]+[a-z0-9_]*$"
re_required_var_classmethod = "^[a-z]+[a-z0-9_]*$"
re_forbidden_assert = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_assert_property = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_checker = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_class = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_function = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_generateblock = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_genvar = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_instance = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_interface = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_localparam = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_modport = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_module_ansi = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_module_nonansi = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_package = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_parameter = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_inout = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_input = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_output = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_ref = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_interface = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_program = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_property = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_sequence = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_task = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_var_class = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_var_classmethod = "^[^X](UNCONFIGURED|.*)$"

[option.unpacked_array]
localparam_declaration = false
param_declaration = false
specparam_declaration = false
inout_declaration = false
ansi_port_declaration = true
input_declaration = true
output_declaration = false
interface_port_declaration = false
ref_declaration = false
data_declaration = true
net_declaration = false

[textrules]
header_copyright = false
style_directives = false
style_semicolon = false
style_textwidth = true

[syntaxrules]
action_block_with_side_effect = false
blocking_assignment_in_always_at_edge = true
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
case_default = true
default_nettype_none = false
enum_with_type = false
eventlist_comma_always_ff = false
eventlist_or = false
explicit_case_default = true
explicit_if_else = false
function_same_as_system_function = false
function_with_automatic = false
general_always_level_sensitive = false
general_always_no_edge = false
generate_case_with_label = true
generate_for_with_label = true
generate_if_with_label = true
genvar_declaration_in_loop = true
genvar_declaration_out_loop = false
implicit_case_default = false
inout_with_tri = false
input_with_var = false
interface_identifier_matches_filename = false
interface_port_with_modport = false
keyword_forbidden_always = true
keyword_forbidden_always_comb = false
keyword_forbidden_always_ff = false
keyword_forbidden_always_latch = false
keyword_forbidden_generate = false
keyword_forbidden_logic = false
keyword_forbidden_priority = false
keyword_forbidden_unique = false
keyword_forbidden_unique0 = true
keyword_forbidden_wire_reg = false
keyword_required_generate = false
localparam_explicit_type = true
localparam_type_twostate = true
loop_statement_in_always_comb = true
loop_statement_in_always_ff = false
loop_statement_in_always_latch = false
loop_variable_declaration = true
lowercamelcase_interface = false
lowercamelcase_module = false
lowercamelcase_package = false
module_ansi_forbidden = false
module_identifier_matches_filename = true
module_nonansi_forbidden = true
multiline_for_begin = false
multiline_if_begin = false
non_blocking_assignment_in_always_comb = true
non_blocking_assignment_in_always_no_edge = true
operator_case_equality = false
operator_incdec = false
operator_self_assignment = false
output_with_var = false
package_identifier_matches_filename = false
package_item_not_in_package = false
parameter_default_value = false
parameter_explicit_type = false
parameter_in_generate = false
parameter_in_package = false
parameter_type_twostate = false
prefix_inout = false
prefix_input = false
prefix_instance = false
prefix_interface = true
prefix_module = false
prefix_output = false
prefix_package = true
procedural_continuous_assignment = false
program_identifier_matches_filename = false
re_forbidden_assert = false
re_forbidden_assert_property = false
re_forbidden_checker = false
re_forbidden_class = false
re_forbidden_function = false
re_forbidden_generateblock = false
re_forbidden_genvar = false
re_forbidden_instance = false
re_forbidden_interface = false
re_forbidden_localparam = false
re_forbidden_modport = false
re_forbidden_module_ansi = false
re_forbidden_module_nonansi = true
re_forbidden_package = false
re_forbidden_parameter = false
re_forbidden_port_inout = false
re_forbidden_port_input = false
re_forbidden_port_interface = false
re_forbidden_port_output = false
re_forbidden_port_ref = false
re_forbidden_program = false
re_forbidden_property = false
re_forbidden_sequence = false
re_forbidden_task = false
re_forbidden_var_class = false
re_forbidden_var_classmethod = false
re_required_assert = true
re_required_assert_property = true
re_required_checker = false
re_required_class = true
re_required_function = true
re_required_generateblock = true
re_required_genvar = true
re_required_instance = false
re_required_interface = true
re_required_localparam = true
re_required_modport = false
re_required_module_ansi = false
re_required_module_nonansi = false
re_required_package = true
re_required_parameter = false
re_required_port_inout = false
re_required_port_input = false
re_required_port_interface = false
re_required_port_output = false
re_required_port_ref = false
re_required_program = false
re_required_property = true
re_required_sequence = false
re_required_task = true
re_required_var_class = false
re_required_var_classmethod = false
sequential_block_in_always_comb = false
sequential_block_in_always_ff = false
sequential_block_in_always_latch = false
style_commaleading = false
style_indent = false
style_keyword_0or1space = true
style_keyword_0space = false
style_keyword_1or2space = true
style_keyword_1space = false
style_keyword_construct = false
style_keyword_datatype = false
style_keyword_end = true
style_keyword_maybelabel = false
style_keyword_new = false
style_keyword_newline = true
style_operator_arithmetic = false
style_operator_arithmetic_leading_space = true
style_operator_boolean = false
style_operator_boolean_leading_space = false
style_operator_integer = false
style_operator_integer_leading_space = false
style_operator_unary = false
style_trailingwhitespace = false
tab_character = false
unpacked_array = true
uppercamelcase_interface = true
uppercamelcase_module = true
uppercamelcase_package = false

